"""Regenerate results/baselines.txt: daily 200-day trend rule and spot grids, with indicator warm-up.

Every block prints the exact `python -m btc_lab backtest ...` command that reproduces it.
Usage: python scripts/make_baselines.py > results/baselines.txt
"""
import json, pathlib, sys
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))
import pandas as pd
from btc_lab.data import load_csv, slice_range, resample
from btc_lab.cli import run_backtest
from btc_lab.engine import FEE_PRESETS
from btc_lab.metrics import by_period

CSV = "data/btcusd_1h_bitstamp.csv.gz"
KEYS = ["start", "end", "total_return_pct", "buy_hold_return_pct", "cagr_pct", "max_drawdown_pct", "n_trades",
        "win_rate_pct", "expectancy_pct_per_trade", "exposure_pct", "fees_pct_of_initial", "sharpe"]


def window(df, start, end=None, warmup_days=250):
    load_start = (pd.Timestamp(start, tz="UTC") - pd.Timedelta(days=warmup_days)).isoformat()
    return slice_range(df, load_start, end)


def main():
    h = load_csv(CSV)
    daily = resample(h, "1D")
    print("# generated by scripts/make_baselines.py; indicators warmed up on 250 days before --start (the CLI default)\n")
    print("=== Daily 200-day MA trend rule (long above, cash below, 2% band) vs hold, coinbase_intro fees")
    print("$ python -m btc_lab backtest --csv data/btcusd_1h_bitstamp.csv.gz --resample 1D --start 2017-06-01 --strategy trend --n 200 --band 2 --fees coinbase_intro")
    d = window(daily, "2017-06-01")
    eng, s = run_backtest(d, "trend", {"n": 200, "band_pct": 2.0}, FEE_PRESETS["coinbase_intro"], 10000,
                          bars_per_year=365, trade_start="2017-06-01")
    print(json.dumps({k: s.get(k) for k in KEYS}))
    print(by_period(eng.state, slice_range(d, "2017-06-01"), "YS", initial_cash=10000).to_string())
    print("\n=== Spot grids, hourly, 2023-01-01 -> end (levels x step), $10k")
    hh = window(h, "2023-01-01")
    for fees in ["zero", "coinbase_intro"]:
        for step, levels in [(1.0, 5), (2.0, 5), (1.0, 10), (3.0, 4)]:
            print(f"$ python -m btc_lab backtest --csv {CSV} --start 2023-01-01 --strategy grid --step {step} --levels {levels} --fees {fees}")
            eng, s = run_backtest(hh, "grid", {"step_pct": step, "levels": levels}, FEE_PRESETS[fees], 10000,
                                  max_positions=levels, trade_start="2023-01-01")
            print(json.dumps({"fees": fees, "step": step, "levels": levels, **{k: s.get(k) for k in KEYS}}))
    print("\n=== Spot grids, 2022 bear year, coinbase_intro")
    h22 = window(h, "2022-01-01", "2023-01-01")
    for step, levels in [(1.0, 5), (2.0, 5)]:
        print(f"$ python -m btc_lab backtest --csv {CSV} --start 2022-01-01 --end 2023-01-01 --strategy grid --step {step} --levels {levels} --fees coinbase_intro")
        eng, s = run_backtest(h22, "grid", {"step_pct": step, "levels": levels}, FEE_PRESETS["coinbase_intro"], 10000,
                              max_positions=levels, trade_start="2022-01-01")
        print(json.dumps({"step": step, "levels": levels, **{k: s.get(k) for k in KEYS}}))


if __name__ == "__main__":
    main()
